
name: Tests

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install nox_poetry
    - name: Cache dataset downloads
      uses: actions/cache@v3
      with:
        # datasets are stored in `~/.data/ea-dataset-provider/`
        path: ~/.data/ea-dataset-provider/
        key: ea-dataset-provider
    - name: list files
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
            ls ~/.data/ea-dataset-provider/
         fi
  shell: bash

    - name: Test with nox
      run: nox -s tests

